### ISSUE TITLE
Count empty dataset throw error instend of 0

### ISSUE THREAD

**Issue by ddecrulle** [InseeFr/Trevas-TS#137]
On my opinion, the size of an empty array `[]` should be 0.

I tested in storybook to do : 

`count(ds)`

with bindings
```json
{
  "ds": {
    "dataStructure": {
      "col_1": {
        "name": "col_1",
        "role": "MEASURE"
      }
    },
    "dataPoints": {
      "col_1": [ ]
    }
  }
}
```

which throw error.

**Comment by laurentC35** [comment]
This line cause this issue : https://github.com/InseeFr/Trevas-JS/blob/master/packages/trevas/src/utils/datasets/operations.js#L72

`r is undefined`

**Comment by NicoLaval** [comment]
Yes, it should be 0.
Bug approved
